export const FETCH_HOTELS_LIST="FETCH_HOTELS_LIST"
export const FILTER_HOTELS_LIST_BY_CATEGORIE="FILTER_HOTELS_LIST_BY_CATEGORIE"
export const ORDER_MOVIES="ORDER_MOVIES"
export const SEARCH_FORM = 'SEARCH_FORM'
