export const FETCH_ALL = 'FETCH_ALL'
export const ORDER_MOVIES_BY_POPULARITY = 'ORDER_MOVIES_BY_POPULARITY'
export const FILTER_MOVIE_B_LANGUAGE = 'FILTER_MOVIE_B_LANGUAGE'
export const SEARCH = 'SEARCH'
export const FILTER_BY_DATE = 'FILTER_BY_DATE'
export const FETCH_POPULARITY = 'FETCH_POPULARITY'




