export const FETCH_ALL = 'FETCH_ALL'
export const FILTER_BY_VOTE_AVERAGE = 'FILTER_BY_VOTE_AVERAGE'
export const FETCH_ALL_HOTELS = 'FETCH_ALL_HOTELS'
export const FILTER_ALL_HOTELS_BY_CATIGORIE = 'FILTER_ALL_HOTELS_BY_CATIGORIE'

