

GET  https://jsonplaceholder.typicode.com/posts

#####
POST  https://jsonplaceholder.typicode.com/posts

Content-Type: application/json

{
    "title":"post_Youssef",
    "body": "this is my post"
}


#####
